Repository AY2021S1-CS2113T-W11-1/tp, pull requests merged in 2020-10, with the labels that each got.

#41 Yu Shing Merge
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/bookmark/Bookmark.java
  src/main/java/seedu/duke/command/AddBookmarkCommand.java
  src/main/java/seedu/duke/command/AddSlotCommand.java
  src/main/java/seedu/duke/command/ChangeModeCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/DeleteBookmarkCommand.java
  src/main/java/seedu/duke/command/DeleteSlotCommand.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/FindBookmarkCommand.java
  src/main/java/seedu/duke/command/LaunchBookmarkCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/ShowTimetableCommand.java
  src/main/java/seedu/duke/exception/DukeExceptionType.java
  src/main/java/seedu/duke/slot/Slot.java
  src/main/java/seedu/duke/slot/SlotList.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, severity.High, type.Enhancement, type.Story

#62 Fix slot commands
  src/main/java/seedu/duke/command/timetable/AddSlotCommand.java
  src/main/java/seedu/duke/command/timetable/DeleteSlotCommand.java
Labels: priority.High, severity.High

#63 Fix nullrange
  data/slot.txt
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/bookmark/BookmarkList.java
  src/main/java/seedu/duke/command/bookmark/DeleteBookmarkCommand.java
  src/main/java/seedu/duke/command/bookmark/LaunchBookmarkCommand.java
  src/main/java/seedu/duke/exception/DukeExceptionType.java
  src/test/java/seedu/duke/bookmark/BookmarkListTest.java
Labels: priority.High, type.Bug

#65 Fix unclear message
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/bookmark/Bookmark.java
  src/main/java/seedu/duke/command/bookmark/DeleteBookmarkCommand.java
  src/main/java/seedu/duke/command/bookmark/FindBookmarkCommand.java
  src/main/java/seedu/duke/command/bookmark/LaunchBookmarkCommand.java
  src/main/java/seedu/duke/command/timetable/AddSlotCommand.java
  src/main/java/seedu/duke/command/timetable/DeleteSlotCommand.java
  src/main/java/seedu/duke/exception/DukeExceptionType.java
  src/test/java/seedu/duke/command/timetable/AddSlotCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#68 markdown for userguide
  docs/UserGuide.md
Labels: priority.High

#69 Update Ui unknown input message
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/timetable/AddSlotCommand.java
  src/main/java/seedu/duke/command/timetable/DeleteSlotCommand.java
  text-ui-test/input.txt
Labels: priority.Medium, severity.Medium

#70 Add timetable add command to user guide
  docs/UserGuide.md
Labels: priority.Medium

#93 Colour and Checkstyle changes
  build.gradle
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/ChangeModeCommand.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/timetable/AddSlotCommand.java
  src/main/java/seedu/duke/command/timetable/DeleteSlotCommand.java
  src/main/java/seedu/duke/command/timetable/ShowTimetableCommand.java
  src/main/java/seedu/duke/slot/Module.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Enhancement

#95 Clear Command
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/ClearCommand.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#101 Merging week 9 changes
  src/main/java/seedu/duke/ItemList.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/bookmark/BookmarkList.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/timetable/ShowTimetableCommand.java
  src/main/java/seedu/duke/exception/DukeExceptionType.java
  src/main/java/seedu/duke/slot/Slot.java
  src/main/java/seedu/duke/slot/SlotList.java
  src/test/java/seedu/duke/DukeTest.java
  src/test/java/seedu/duke/bookmark/BookmarkTest.java
  src/test/java/seedu/duke/command/ChangeModeCommandTest.java
  src/test/java/seedu/duke/command/timetable/ShowTimetableCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, severity.High, type.Enhancement

#104 Gson saving
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/ChangeModeCommand.java
  src/main/java/seedu/duke/command/ClearCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/bookmark/AddBookmarkCommand.java
  src/main/java/seedu/duke/command/bookmark/DeleteBookmarkCommand.java
  src/main/java/seedu/duke/command/bookmark/FindBookmarkCommand.java
  src/main/java/seedu/duke/command/bookmark/LaunchBookmarkCommand.java
  src/main/java/seedu/duke/command/bookmark/ShowBookmarkCommand.java
  src/main/java/seedu/duke/command/timetable/AddSlotCommand.java
  src/main/java/seedu/duke/command/timetable/DeleteSlotCommand.java
  src/main/java/seedu/duke/command/timetable/ShowTimetableCommand.java
Labels: priority.High, severity.High, type.Task

#111 Jar File Pathing
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/timetable/AddSlotCommand.java
  src/main/java/seedu/duke/slot/Module.java
  src/main/java/seedu/duke/slot/Timetable.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Enhancement

#118 Implement EditSlotCommand
  src/main/java/seedu/zoomaster/Parser.java
  src/main/java/seedu/zoomaster/command/planner/AddMeetingCommand.java
  src/main/java/seedu/zoomaster/command/timetable/AddSlotCommand.java
  src/main/java/seedu/zoomaster/command/timetable/EditSlotCommand.java
  src/main/java/seedu/zoomaster/slot/Module.java
  src/main/java/seedu/zoomaster/slot/Timetable.java
Labels: priority.High, severity.High, type.Story

#123 Helpcommand
  src/main/java/seedu/zoomaster/Parser.java
  src/main/java/seedu/zoomaster/Ui.java
  src/main/java/seedu/zoomaster/bookmark/Bookmark.java
  src/main/java/seedu/zoomaster/command/ExitCommand.java
  src/main/java/seedu/zoomaster/command/HelpCommand.java
  src/main/java/seedu/zoomaster/command/LaunchNowCommand.java
  src/main/java/seedu/zoomaster/command/bookmark/AddBookmarkCommand.java
  src/main/java/seedu/zoomaster/command/bookmark/DeleteBookmarkCommand.java
  src/main/java/seedu/zoomaster/command/bookmark/ShowBookmarkCommand.java
  src/main/java/seedu/zoomaster/exception/ZoomasterExceptionType.java
  src/main/java/seedu/zoomaster/slot/Module.java
Labels: priority.Medium, type.Enhancement

#125 Fix edit slot
  src/main/java/seedu/zoomaster/command/timetable/ShowTimetableCommand.java
  src/main/java/seedu/zoomaster/slot/SlotContainer.java
  src/main/java/seedu/zoomaster/slot/Timetable.java
Labels: priority.High, severity.High, type.Enhancement

#131 Updating UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/current time indicator.png
  docs/diagrams/exit.png
  docs/diagrams/help 1.png
  docs/diagrams/help 2.png
  docs/diagrams/help 3.png
  docs/diagrams/help add msg.png
  docs/diagrams/help add.png
  docs/diagrams/help cmd bkmrk.png
  docs/diagrams/help cmd main.png
  docs/diagrams/help cmd time.png
  docs/diagrams/lesson now indicator.png
  docs/diagrams/mode 1.png
  docs/diagrams/mode 2.png
  docs/diagrams/mode 3.png
  docs/diagrams/show all list.png
  docs/diagrams/show empty list.png
  docs/diagrams/show today list.png
  docs/diagrams/show wed list.png
Labels: priority.Low, severity.Low, type.Task

#174 Changed bookmark colour to cyan and planner to magenta
  src/main/java/seedu/zoomaster/Parser.java
  src/main/java/seedu/zoomaster/Ui.java
Labels: type.Enhancement

#176 Changed colour for current time indicator
  src/main/java/seedu/zoomaster/command/timetable/ShowTimetableCommand.java
Labels: priority.Low, severity.Low, type.Enhancement

#180 Fix dry run error messages
  src/main/java/seedu/zoomaster/Ui.java
  src/main/java/seedu/zoomaster/bookmark/Bookmark.java
  src/main/java/seedu/zoomaster/bookmark/BookmarkList.java
  src/main/java/seedu/zoomaster/command/timetable/AddSlotCommand.java
  src/main/java/seedu/zoomaster/exception/ZoomasterExceptionType.java
  src/test/java/seedu/zoomaster/bookmark/BookmarkListTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium
