Repository AY2021S1-CS2113T-W11-1/tp, pull requests merged in 2020-11, with the labels that each got.

#182 Fix filepath storage on mac
  src/main/java/seedu/zoomaster/Storage.java
Labels: priority.High, severity.High

#183 Fix edit command error
  src/main/java/seedu/zoomaster/Ui.java
  src/main/java/seedu/zoomaster/command/timetable/EditSlotCommand.java
  src/main/java/seedu/zoomaster/exception/ZoomasterExceptionType.java
Labels: priority.High, severity.High

#189 Add test for EditSlotCommand
  src/test/java/seedu/zoomaster/command/timetable/EditSlotCommandTest.java
Labels: priority.High, severity.Medium

#191 Quick fix to storage
  src/main/java/seedu/zoomaster/Storage.java
  src/test/java/seedu/zoomaster/command/timetable/EditSlotCommandTest.java
Labels: priority.High, severity.High

#194 Edit bookmark
  src/main/java/seedu/zoomaster/Parser.java
  src/main/java/seedu/zoomaster/bookmark/Bookmark.java
  src/main/java/seedu/zoomaster/command/bookmark/EditBookmarkCommand.java
  src/test/java/seedu/zoomaster/command/bookmark/EditBookmarkCommandTest.java
Labels: priority.High, severity.High, type.Story

#200 Logo + Bugfix
  src/main/java/seedu/zoomaster/Storage.java
  src/main/java/seedu/zoomaster/Ui.java
  src/main/java/seedu/zoomaster/bookmark/BookmarkList.java
  src/test/java/seedu/zoomaster/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Bug, type.Enhancement

#203 AboutUs photos update, some changes to Userguide
  docs/AboutUs.md
  docs/UserGuide.md
  src/main/java/seedu/zoomaster/Parser.java
  src/main/java/seedu/zoomaster/Ui.java
Labels: priority.Medium, screenshot

#205 Reposense
  src/main/java/seedu/zoomaster/Storage.java
  src/main/java/seedu/zoomaster/Ui.java
  src/main/java/seedu/zoomaster/Zoomaster.java
  src/main/java/seedu/zoomaster/bookmark/Bookmark.java
  src/main/java/seedu/zoomaster/bookmark/BookmarkList.java
  src/main/java/seedu/zoomaster/command/bookmark/AddBookmarkCommand.java
  src/main/java/seedu/zoomaster/command/bookmark/DeleteBookmarkCommand.java
  src/main/java/seedu/zoomaster/command/bookmark/EditBookmarkCommand.java
  src/main/java/seedu/zoomaster/command/bookmark/FindBookmarkCommand.java
  src/main/java/seedu/zoomaster/command/bookmark/LaunchBookmarkCommand.java
  src/main/java/seedu/zoomaster/command/bookmark/ShowBookmarkCommand.java
  src/main/java/seedu/zoomaster/command/settings/SetSettingsCommand.java
  src/main/java/seedu/zoomaster/command/settings/ShowSettingsCommand.java
  src/main/java/seedu/zoomaster/settings/SettingsVariable.java
  src/main/java/seedu/zoomaster/settings/UserSettings.java
  src/test/java/seedu/zoomaster/ParserTest.java
  src/test/java/seedu/zoomaster/StorageTest.java
Labels: priority.Medium

#219 Added a few image containers for future screenshots to be added
  docs/UserGuide.md
Labels: priority.Medium, severity.VeryLow

#222 Add authorships comments
  src/main/java/seedu/zoomaster/Storage.java
  src/main/java/seedu/zoomaster/command/bookmark/EditBookmarkCommand.java
  src/main/java/seedu/zoomaster/command/settings/SetSettingsCommand.java
  src/main/java/seedu/zoomaster/command/settings/ShowSettingsCommand.java
  src/main/java/seedu/zoomaster/command/timetable/EditSlotCommand.java
  src/main/java/seedu/zoomaster/settings/SettingsVariable.java
  src/main/java/seedu/zoomaster/settings/UserSettings.java
Labels: priority.Medium, severity.Low

#226 Add show and set settings to devguide
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Task

#227 Fix edit and settins error handling
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/zoomaster/Ui.java
  src/main/java/seedu/zoomaster/Zoomaster.java
  src/main/java/seedu/zoomaster/command/Mode.java
  src/main/java/seedu/zoomaster/command/bookmark/EditBookmarkCommand.java
  src/main/java/seedu/zoomaster/command/settings/SetSettingsCommand.java
  src/main/java/seedu/zoomaster/exception/ZoomasterExceptionType.java
  src/main/java/seedu/zoomaster/settings/SettingsVariable.java
  src/main/java/seedu/zoomaster/settings/UserSettings.java
Labels: priority.Medium, severity.Medium

#236 Newdeveloper
  docs/DeveloperGuide.md
  docs/diagrams/loadModuleList/getModuleList.png
  docs/diagrams/loadModuleList/getModuleList.puml
  docs/diagrams/loadModuleList/helpCommandOverallDiagram.png
  docs/diagrams/loadModuleList/helpCommandOverallDiagram.puml
  docs/images/architecture.png
  docs/images/initial.png
  docs/images/zoomasterwhitebg.png
  src/main/java/seedu/zoomaster/Storage.java
  src/main/java/seedu/zoomaster/Ui.java
  src/main/java/seedu/zoomaster/Zoomaster.java
  src/test/java/seedu/zoomaster/ZoomasterTest.java
Labels: priority.High

#240 Fixes to DG
  docs/DeveloperGuide.md
Labels: priority.Medium, severity.Low

#243 broke up sequence diagrams, edited parsercommand diagrams
  docs/DeveloperGuide.md
  docs/diagrams/loadModuleList/helpCommandDetailsIsEmpty.png
  docs/diagrams/loadModuleList/helpCommandDetailsIsEmpty.puml
  docs/diagrams/loadModuleList/helpCommandDetailsNotEmpty.png
  docs/diagrams/loadModuleList/helpCommandDetailsNotEmpty.puml
  docs/diagrams/loadModuleList/helpCommandOverallDiagram.png
  docs/diagrams/loadModuleList/helpCommandOverallDiagram.puml
  docs/images/parsercommand/mode0.png
  docs/images/parsercommand/mode1.png
  docs/images/parsercommand/mode2.png
  docs/images/parsercommand/mode3.png
  src/main/java/seedu/zoomaster/command/HelpCommand.java
Labels: priority.High

#248 JUnit test for HelpCommand, Fixed some image linking
  docs/DeveloperGuide.md
  src/main/java/seedu/zoomaster/command/HelpCommand.java
  src/test/java/seedu/zoomaster/StorageTest.java
  src/test/java/seedu/zoomaster/command/HelpCommandTest.java
Labels: priority.High

#260 user guide changes
  docs/UserGuide.md
  docs/images/buglogo.png
  src/main/java/seedu/zoomaster/slot/Timetable.java
Labels: priority.High
